apiVersion: apps/v1
kind: Deployment
metadata:
  name: barramento-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: barramento
  template:
    metadata:
      labels:
        app: barramento

    spec:
      containers:
        - name: barramento
          image: pauloeduardo0123/barramento
          imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: barramento

spec:
  selector:
    app: barramento

#ip interno ao cluster
  type: ClusterIP
  ports:
    - name: barramento
      protocol: TCP
      port: 10000
      targetPort: 10000