apiVersion: apps/v1
kind: Deployment
metadata:
    name: lembretes-deployment

spec:
    replicas: 1
    selector:
        matchLabels:
            app: lembretes
    
    template:
        metadata:
            labels:
                app: lembretes
        
        spec:
          containers:
            - name: lembretes
              image: pauloeduardo0123/lembretes
              imagePullPolicy: Always
              resources:
                limits:
                    memory: 256Mi
                    cpu: 1

---

apiVersion: v1
kind: Service
metadata:
#nome diferente do outro de tipo NodePort
#que havíamos criado
    name: lembretes-clusterip-service

spec:
    selector:
        app: lembretes
    ports:
        - name: lembretes
          protocol: TCP
          port: 4000
          targetPort: 4000